List<Map<String, String>> data = [
  {
    'subject': 'Big data',
    'title': 'What is Big Data?',
    'content': '''
      Big Data refers to the massive volume of structured and unstructured data that organizations collect and process on a daily basis. It encompasses data from various sources, including social media, sensors, websites, and more.
      
      Organizations use Big Data to gain insights, make informed decisions, and improve their operations. It often involves technologies like Hadoop, Spark, and NoSQL databases.
      
      Big Data has three primary characteristics: volume (large amounts of data), velocity (data generated rapidly), and variety (diverse data types).
      
      Harnessing Big Data can lead to improved business intelligence, predictive analytics, and better understanding of customer behavior.
    ''',
  },
  {
    'subject': 'BigData',
    'title': 'Challenges of Big Data',
    'content': '''
      While Big Data offers numerous benefits, it also presents challenges. One key challenge is data management. Storing and processing vast amounts of data require specialized infrastructure and tools.
      
      Another challenge is data quality. Big Data often includes noisy or incomplete data, making it crucial to clean and preprocess it before analysis.
      
      Privacy and security concerns are significant. Handling sensitive data at a large scale raises issues related to data breaches and compliance with regulations.
      
      Scalability is vital in Big Data solutions. As data volumes grow, systems need to scale seamlessly to handle the increased load.
      
      Finding skilled data professionals who can work with Big Data technologies is also a challenge.
    ''',
  },
  {
    'subject': 'Big Data',
    'title': 'Applications of Big Data',
    'content': '''
      Big Data has applications across various industries. In healthcare, it can be used for disease prediction and drug discovery.
      
      Retailers use Big Data for personalized marketing and inventory management.
      
      Financial institutions employ it for fraud detection and risk analysis.
      
      In transportation, Big Data helps optimize routes and improve logistics.
      
      Governments use Big Data for urban planning and disaster response.
    ''',
  },
  {
    'subject': 'Big data',
    'title': 'Technologies in Big Data',
    'content': '''
      Hadoop is a popular open-source framework for distributed storage and processing of Big Data. It uses the Hadoop Distributed File System (HDFS) and MapReduce for computation.
      
      Apache Spark is known for its in-memory processing capabilities, making it faster than Hadoop for certain tasks.
      
      NoSQL databases like MongoDB and Cassandra are used for handling unstructured and semi-structured data.
      
      Machine learning and AI are integrated into Big Data solutions for predictive analytics and data-driven insights.
      
      Data visualization tools help analysts and decision-makers understand and interpret Big Data.
    ''',
  },
  {
    'subject': 'Big Data',
    'title': 'Future Trends in Big Data',
    'content': '''
      The future of Big Data includes even larger data volumes, generated by IoT devices and other sources.
      
      Edge computing, which processes data closer to its source, will gain importance to reduce latency and bandwidth usage.
      
      Data privacy and ethics will become more significant concerns, leading to stricter regulations.
      
      Machine learning and AI will continue to play a crucial role in automating data analysis and decision-making.
      
      Hybrid and multicloud architectures will be used for scalable and cost-effective Big Data solutions.
    ''',
  },
];
List<Map<String, String>> images = [
  {
    "search":
        "https://cdn.vectorstock.com/i/1000x1000/78/07/icon-with-search-3d-for-web-site-design-vector-44467807.webp",
  },
  {
    "subject":
        "https://as1.ftcdn.net/v2/jpg/04/37/98/00/1000_F_437980063_FWUOWACHLH8kCDxTz0JybPCJa3jBWl2c.jpg"
  }
];
