// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_ov82MZz2vveVzMdnq-eeB3RQUrb6ZjU',
    appId: '1:232514177265:web:063f562fb4d33e0dcdc150',
    messagingSenderId: '232514177265',
    projectId: 'thenotesapp-97c49',
    authDomain: 'thenotesapp-97c49.firebaseapp.com',
    databaseURL: 'https://thenotesapp-97c49-default-rtdb.firebaseio.com',
    storageBucket: 'thenotesapp-97c49.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5APnLDOK0d2ZFUnY2CDyYtE1Gv_qCWDg',
    appId: '1:232514177265:android:c9b8785c75d2c69dcdc150',
    messagingSenderId: '232514177265',
    projectId: 'thenotesapp-97c49',
    databaseURL: 'https://thenotesapp-97c49-default-rtdb.firebaseio.com',
    storageBucket: 'thenotesapp-97c49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBBPpaq4h67NSKP981I6qyg-PBcLbYlk0',
    appId: '1:232514177265:ios:37843379397d855acdc150',
    messagingSenderId: '232514177265',
    projectId: 'thenotesapp-97c49',
    databaseURL: 'https://thenotesapp-97c49-default-rtdb.firebaseio.com',
    storageBucket: 'thenotesapp-97c49.appspot.com',
    iosBundleId: 'com.example.secretNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBBPpaq4h67NSKP981I6qyg-PBcLbYlk0',
    appId: '1:232514177265:ios:caaf8f86928aed31cdc150',
    messagingSenderId: '232514177265',
    projectId: 'thenotesapp-97c49',
    databaseURL: 'https://thenotesapp-97c49-default-rtdb.firebaseio.com',
    storageBucket: 'thenotesapp-97c49.appspot.com',
    iosBundleId: 'com.example.secretNotes.RunnerTests',
  );
}
